import Foundation

/// Builds a shareable Markdown report: cash flow, category breakdown, top
/// merchants, debt snapshot, goal progress and the current paycheck plan.
enum ReportGenerator {

    static func monthlyReport(
        transactions: [BankTransaction],
        accounts: [FinancialAccount],
        goals: [SavingsGoal],
        plan: AllocationPlan?,
        reference: Date = Date()
    ) -> String {
        let calendar = Calendar.current
        guard let interval = calendar.dateInterval(of: .month, for: reference) else { return "" }

        let monthTransactions = transactions.filter { interval.contains($0.date) }
        let income = monthTransactions.filter { $0.amount > 0 }.reduce(0) { $0 + $1.amount }
        let spending = monthTransactions.filter { $0.amount < 0 }.reduce(0) { $0 + abs($1.amount) }

        var lines: [String] = []
        lines.append("# PaycheckPilot Report — \(reference.formatted(.dateTime.month(.wide).year()))")
        lines.append("")

        lines.append("## Cash flow this month")
        lines.append("- Income: \(income.currency)")
        lines.append("- Spending: \(spending.currency)")
        lines.append("- Net: \((income - spending).currency)")
        if income > 0 {
            let rate = max(0, (income - spending) / income)
            lines.append("- Savings rate: \(rate.formatted(.percent.precision(.fractionLength(0))))")
        }
        lines.append("")

        var categoryTotals: [SpendingCategory: Double] = [:]
        for transaction in monthTransactions where transaction.amount < 0 {
            categoryTotals[transaction.category, default: 0] += abs(transaction.amount)
        }
        if !categoryTotals.isEmpty {
            lines.append("## Spending by category")
            for (category, total) in categoryTotals.sorted(by: { $0.value > $1.value }) {
                lines.append("- \(category.displayName): \(total.currency)")
            }
            lines.append("")
        }

        let merchants = InsightsEngine.topMerchants(transactions: transactions, days: 30, reference: reference)
        if !merchants.isEmpty {
            lines.append("## Top merchants (last 30 days)")
            for merchant in merchants {
                lines.append("- \(merchant.payee): \(merchant.total.currency)")
            }
            lines.append("")
        }

        let debts = accounts.filter { $0.kind.isDebt && $0.currentBalance > 0 }
        if !debts.isEmpty {
            lines.append("## Debt snapshot")
            for debt in debts.sorted(by: { $0.currentBalance > $1.currentBalance }) {
                let apr = debt.apr.formatted(.number.precision(.fractionLength(1)))
                lines.append("- \(debt.name): \(debt.currentBalance.currency) at \(apr)% APR (min \(debt.minimumPayment.currency)/mo)")
            }
            let totalDebt = debts.reduce(0) { $0 + $1.currentBalance }
            lines.append("- **Total: \(totalDebt.currency)**")
            lines.append("")
        }

        if !goals.isEmpty {
            lines.append("## Savings goals")
            for goal in goals.sorted(by: { $0.targetDate < $1.targetDate }) {
                let percent = goal.progress.formatted(.percent.precision(.fractionLength(0)))
                let due = goal.targetDate.formatted(date: .abbreviated, time: .omitted)
                lines.append("- \(goal.name): \(goal.savedAmount.currency) of \(goal.targetAmount.currency) (\(percent)) — target \(due)")
            }
            lines.append("")
        }

        if let plan {
            lines.append("## Current paycheck plan (updated \(plan.generatedAt.formatted(date: .abbreviated, time: .omitted)))")
            for line in plan.sortedLines {
                lines.append("- \(line.label): \(line.amount.currency) — \(line.detail)")
            }
            lines.append("")
        }

        lines.append("---")
        lines.append("Generated by PaycheckPilot. Informational only — not financial advice.")
        return lines.joined(separator: "\n")
    }
}
